### ISSUE TITLE
Complete Wiki page

### ISSUE THREAD

**Issue by Victoriaia1** [Victoriaia1/Integrate#5]

**Comment by Victoriaia1** [comment]
Hi team,
Please let's complete the following tasks on Wiki - GitHub

- [x] Complete introduction
- [x] Complete resource needs
- [x] Complete stakeholder register
- [x] Complete Gantt chart
- [x] Complete Persona
- [x] Complete testing
- [x] Complete risks

**Comment by wuyvshiqi** [comment]
ok

**Comment by wuyvshiqi** [comment]
ok

**Comment by Karlsase** [comment]
ok

**Comment by Victoriaia1** [comment]
ok, we completed the tasks all mentioned above .
https://github.com/Victoriaia1/Group19
